# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paul Bartlett's Broken Webpage
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is DOWN unless you are looking for a blank page
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://paul-bartlett.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  paul-bartlett

# Build settings
markdown: kramdown
